python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=0
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=0
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=1
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=1
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=2
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=2
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=3
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=3
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=4
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=4
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=5
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=5
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=6
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=6
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=7
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=7
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=8
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=8
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=adult_income --model_class=AdaBoost --nbr_evals=25 --rseed=9
python train_models.py --dataset=adult_income --model_class=DNN --nbr_evals=25 --rseed=9
python train_models.py --dataset=adult_income --model_class=RF --nbr_evals=25 --rseed=9
python train_models.py --dataset=adult_income --model_class=XgBoost --nbr_evals=25 --rseed=9
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=0
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=0
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=1
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=1
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=2
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=2
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=3
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=3
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=4
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=4
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=5
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=5
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=6
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=6
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=7
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=7
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=8
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=8
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=compas --model_class=AdaBoost --nbr_evals=25 --rseed=9
python train_models.py --dataset=compas --model_class=DNN --nbr_evals=25 --rseed=9
python train_models.py --dataset=compas --model_class=RF --nbr_evals=25 --rseed=9
python train_models.py --dataset=compas --model_class=XgBoost --nbr_evals=25 --rseed=9
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=0
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=0
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=1
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=1
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=2
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=2
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=3
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=3
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=4
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=4
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=5
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=5
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=6
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=6
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=7
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=7
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=8
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=8
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=default_credit --model_class=AdaBoost --nbr_evals=25 --rseed=9
python train_models.py --dataset=default_credit --model_class=DNN --nbr_evals=25 --rseed=9
python train_models.py --dataset=default_credit --model_class=RF --nbr_evals=25 --rseed=9
python train_models.py --dataset=default_credit --model_class=XgBoost --nbr_evals=25 --rseed=9
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=0
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=0
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=0
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=1
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=1
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=1
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=2
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=2
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=2
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=3
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=3
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=3
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=4
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=4
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=4
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=5
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=5
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=5
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=6
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=6
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=6
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=7
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=7
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=7
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=8
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=8
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=8
python train_models.py --dataset=marketing --model_class=AdaBoost --nbr_evals=25 --rseed=9
python train_models.py --dataset=marketing --model_class=DNN --nbr_evals=25 --rseed=9
python train_models.py --dataset=marketing --model_class=RF --nbr_evals=25 --rseed=9
python train_models.py --dataset=marketing --model_class=XgBoost --nbr_evals=25 --rseed=9
